# Generated by Django 4.0.4 on 2022-04-18 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='categories',
            field=models.ManyToManyField(to='charity.category', verbose_name='Kategorii'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.institution', verbose_name='Instytucji'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.IntegerField(verbose_name='Ilość'),
        ),
    ]
