# Generated by Django 4.0.4 on 2022-04-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_alter_donation_phone_number_alter_donation_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('fundacja', 'Fundacja'), ('organ. pazarządowa', 'Organizacja pozarządowa'), ('zbiórka lokalna', 'Zbiórka lokalna')], default='Fundacja', max_length=100, verbose_name='Typ organizacji'),
        ),
    ]
